spring.application.name=writewise-learning-service
ollama-llm-writing-module-topics=http://cloud-llm-service-k8s.default.svc.cluster.local:7070/api/v2/llm/text
model-name=gpt-oss:120b
app-util-service=http://writewise-learning-service-k8s.default.svc.cluster.local:8989/api/writewise/v1/word/metadata
