spring.application.name=writewise-learning-service
#ollama-llm-writing-module-topics=http://192.168.1.90:31434/api/v1/llm/text/
ollama-llm-writing-module-topics=http://192.168.1.90:31435/api/v2/llm/text
model-name=gpt-oss:120b
app-util-service=http://192.168.1.90:31371/api/