spring.application.name=writewise-learning-service
ollama-llm-writing-module-topics=http://llm-service-k8s.default.svc.cluster.local:6565/api/v1/llm/text/
model-name=llama3.2
app-util-service=http://writewise-learning-service-k8s.default.svc.cluster.local:8989/api/writewise/v1/word/metadata
