spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/
      #      database: ${MONGODB_DATABASE:writewise}
      #      username: ${MONGODB_USERNAME:mongoroot}
      #      password: ${MONGODB_PASSWORD:mongopass}
  #      host: ${MONGODB_HOST:localhost}
  #      port: ${MONGODB_PORT:27017}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    username: ${MYSQL_USER:abhishek}
    password: ${MYSQL_PASSWORD:abhishek}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:abhishek}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 50
server:
  port: ${SERVICE_PORT:8989}