ollama-llm-based-evaluator=http://llm-service-k8s.default.svc.cluster.local:6565/api/v1/llm/evaluation/meaning/
writewise-llm-service=http://leximentor-util-service-k8s.default.svc.cluster.local:4545/api/
ollama-llm-writing-module-topics=http://llm-service-k8s.default.svc.cluster.local:6565/api/v1/llm/text/
model-name=ministral-3:3b