package com.abhi.leximentor.fitmate.mapper;

import com.abhi.leximentor.fitmate.dto.TrainingDTO;
import com.abhi.leximentor.fitmate.entities.Training;
import com.abhi.leximentor.fitmate.util.KeyGeneratorUtil;
import org.mapstruct.*;

/**
 * MapStruct mapper for {@link Training} ↔ {@link TrainingDTO}.
 *
 * <p>Replaces {@code FitmateServiceUtil.TrainingMetadataUtil}.</p>
 */
@Mapper(
        componentModel = "spring",
        uses = {FitmateMapperHelper.class},
        unmappedTargetPolicy = ReportingPolicy.IGNORE
)
public interface TrainingMapper {

    // -----------------------------------------------------------------------
    // Entity → DTO
    // -----------------------------------------------------------------------

    @Mapping(target = "refId",  source = "refId",  qualifiedByName = "longToString")
    @Mapping(target = "status", source = "status",  qualifiedByName = "applicationStatusToString")
    TrainingDTO toDto(Training entity);

    // -----------------------------------------------------------------------
    // DTO → Entity
    // -----------------------------------------------------------------------

    /**
     * Creates a new {@link Training} entity from a DTO.
     *
     * <ul>
     *   <li>{@code id}        — managed by JPA; ignored.</li>
     *   <li>{@code uuid}      — generated by {@link KeyGeneratorUtil#uuid()}.</li>
     *   <li>{@code refId}     — generated by {@link KeyGeneratorUtil#refId()}.</li>
     *   <li>{@code excercises}— relationship; ignored on creation.</li>
     *   <li>{@code crtnDate} / {@code lastUpdDate} — managed by Hibernate; ignored.</li>
     * </ul>
     */
    @Mapping(target = "id",         ignore = true)
    @Mapping(target = "uuid",       expression = "java(com.abhi.leximentor.fitmate.util.KeyGeneratorUtil.uuid())")
    @Mapping(target = "refId",      expression = "java(com.abhi.leximentor.fitmate.util.KeyGeneratorUtil.refId())")
    @Mapping(target = "status",     source = "status", qualifiedByName = "applicationStatusToInt")
    @Mapping(target = "excercises", ignore = true)
    @Mapping(target = "crtnDate",   ignore = true)
    @Mapping(target = "lastUpdDate",ignore = true)
    Training toEntity(TrainingDTO dto);
}
