version: '3.1'

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 5050:8080
    depends_on:
      - zookeeper
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-service
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-service
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
  mysql:
    image: mysql:latest
    container_name: mysql-service
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abhishek
      MYSQL_USER: abhishek
      MYSQL_PASSWORD: abhishek
      MYSQL_DATABASE: abhishek
  inventory:
    image: inventory-service:latest
    container_name: inventory-service
    ports:
      - "9191:9191"
    depends_on:
      - mysql