version: '3.1'

services:
  #  kafka-ui:
  #    container_name: kafka-ui
  #    image: provectuslabs/kafka-ui:latest
  #    ports:
  #      - 5050:8080
  #    depends_on:
  #      - zookeeper
  #      - kafka
  #    environment:
  #      DYNAMIC_CONFIG_ENABLED: 'true'
  #  zookeeper:
  #    image: wurstmeister/zookeeper
  #    container_name: zookeeper-service
  #    ports:
  #      - "2181:2181"
  #  kafka:
  #    image: gwilym/wurstmeister-kafka-docker
  #    container_name: kafka-service
  #    ports:
  #      - "9092:9092"
  #    environment:
  #      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://192.168.1.7:9092
  #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
  #      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
  mysql:
    image: mysql:latest
    container_name: mysql-service
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abhishek
      MYSQL_USER: abhishek
      MYSQL_PASSWORD: abhishek
      MYSQL_DATABASE: abhishek
    volumes:
      - mysql-data:/var/lib/mysql
  inventory:
    image: inventory-service:latest
    container_name: inventory-service
    ports:
      - "9191:9191"
    depends_on:
      - mysql
  synapster:
    image: synapster-learning-service:latest
    container_name: synapster-learning-service
    ports:
      - "9292:9292"
    depends_on:
      - mysql
  fitmate:
    image: fitmate-service:latest
    container_name: fitmate-service
    ports:
      - "9393:9393"
    depends_on:
      - mysql
  nltk:
    image: nltk-word-service:latest
    container_name: nltk-word-service
    ports:
      - "5600:5600"
  datamuse:
    image: datamuse-word-service:latest
    container_name: datamuse-word-service
    ports:
      - "7700:7700"
  meaning:
    image: meaning-evaluation-service-llm:latest
    container_name: meaning-evaluation-service-llm
    ports:
      - "7300:7300"
  ui:
    image: leximentor-ui-service:latest
    container_name: leximentor-ui-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - inventory
  speech:
    image: speech-from-text-service:latest
    container_name: speech-from-text-service
    ports:
      - "8300:8300"

volumes:
  mysql-data: