apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  type: ExternalName
  externalName: 192.168.1.6

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-service-app
  template:
    metadata:
      labels:
        app: ollama-service-app
    spec:
      containers:
        - name: ollama-service-app
          image: localhost:5000/ll-service:latest
          env:
            - name: LLAMA_HOST
              value: "llm-service"
            - name: LLAMA_PORT
              value: "11434"
          ports:
            - containerPort: 6565