apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-service-config
data:
  LLAMA_HOST: "192.168.1.3"
  LLAMA_PORT: "11434"

---

apiVersion: v1
kind: Service
metadata:
  name: llm-service-k8s
spec:
  selector:
    app: llm-app
  ports:
    - port: 6565
      targetPort: 6565
      nodePort: 31434
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-app
  template:
    metadata:
      labels:
        app: llm-app
    spec:
      containers:
        - name: llm-service-app
          image: localhost:5000/llm-service:latest
          env:
            - name: LLAMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: llama-service-config
                  key: LLAMA_HOST
            - name: LLAMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: llama-service-config
                  key: LLAMA_PORT
          ports:
            - containerPort: 6565