# Apply the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-k8s
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: localhost:5000/nginx-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
---

# Adding the service

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-k8s
spec:
  selector:
    app: nginx-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort # or NodePort, ClusterIP, etc. depending on your needs
