server:
  port: 9393
spring:
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      value-serializer: com.abhi.leximentor.publisher.service.WordDTOSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer