spring:
  profiles:
    active: prod
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    username: ${MYSQL_USER:abhishek}
    password: ${MYSQL_PASSWORD:abhishek}
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.90}:${MYSQL_PORT:31124}/${MYSQL_DATABASE:abhishek}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 600000
      maximum-pool-size: 50
      max-lifetime: 1800000
      validation-timeout: 5000
      keepalive-time: 300000
#  kafka:
#    consumer:
#      bootstrap-servers: 192.168.1.7:9092
#      group-id: word-group-1
server:
  port: ${SERVICE_PORT:9191}

leximentor:
  services:
    app-llm:
      service:
        base-url: http://llm-service-k8s.default.svc.cluster.local:6565/api/v1/llm/evaluation/meaning/
    ollama:
      service:
        base-url: http://192.168.1.90:31434/api/v2/llm/text
      model:
        name: ministral-3:3b
    writewise:
      service:
        base-url: http://leximentor-util-service-k8s.default.svc.cluster.local:4545/api/