spring:
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    username: ${MYSQL_USER:abhishek}
    password: ${MYSQL_PASSWORD:abhishek}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:abhishek}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 600000
      maximum-pool-size: 50
      max-lifetime: 1800000
      validation-timeout: 5000
      keepalive-time: 300000
#  kafka:
#    consumer:
#      bootstrap-servers: 192.168.1.7:9092
#      group-id: word-group-1
server:
  port: ${SERVICE_PORT:9191}