spring:
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    username: abhishek
    password: abhishek
    url: jdbc:mysql://192.168.1.2:3306/abhishek
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 50
  application:
    name: synapster-learning-service
server:
  port: 9292